//Aqui temos os livros sendo "cadastrados" na lista books. O id é o que torna cada um exlusivo.

export const books = [
  {
    id: '1',
    name: 'O Mundo de Sofia',
    value: 13.78,
    autor: 'Jostein Gaarder',
    editora: 'Cia das Letras',
    image: 'https://m.media-amazon.com/images/I/81KfUf8JkcL._SY425_.jpg',
  },
  {
    id: '2',
    name: 'É Assim que Acaba',
    value: 19.9,
    autor: 'Colleen Hoover',
    editora: 'Galera',
    image: 'https://m.media-amazon.com/images/I/91r5G8RxqfL._SL1500_.jpg',
  },
  {
    id: '3',
    name: 'A Biblioteca da Meia-Noite',
    value: 9.52,
    autor: ' Matt Haig',
    editora: 'Bertrand Brasil',
    image: 'https://m.media-amazon.com/images/I/81iqH8dpjuL._SL1500_.jpg',
  },
  {
    id: '4',
    name: 'Os sete maridos de Evelyn Hugo',
    value: 17.47,
    autor: ' Taylor Jenkins Reid',
    editora: 'Paralela',
    image: 'https://m.media-amazon.com/images/I/91yEPgRcELL._SL1500_.jpg',
  },
  {
    id: '5',
    name: '1984',
    value: 17.99,
    autor: 'George Orwell',
    editora: 'Cia das Letras',
    image: 'https://m.media-amazon.com/images/I/819js3EQwbL._SL1500_.jpg',
  },
  {
    id: '6',
    name: 'Irmãos Karamazov',
    value: 28.79,
    autor: ' Dostoiévski',
    editora: 'Garnier',
    image: 'https://m.media-amazon.com/images/I/81IGywQ0B1L._SL1500_.jpg',
  },
  {
    id: '7',
    name: 'Os crimes ABC',
    value: 8.89,
    autor: 'Agatha Christie',
    editora: 'HarperCollins',
    image: 'https://m.media-amazon.com/images/I/81rqjb5EIdL._SL1500_.jpg',
  },
  {
    id: '8',
    name: 'O Caçador de Pipas',
    value: 14.10,
    autor: 'Khaled Hosseini ',
    editora: 'Globo Livros',
    image: 'https://m.media-amazon.com/images/I/81Ylg3mdxGL._SL1500_.jpg',
  },
  {
    id: '9',
    name: 'Ciranda de Pedra',
    value: 9.90,
    autor: 'Lygia Fagundes Telles',
    editora: 'Cia das Letras',
    image: 'https://m.media-amazon.com/images/I/91dOX6mr9nS._SL1500_.jpg',
  },
  {
    id: '10',
    name: 'A Hora da Estrela',
    value: 22.25,
    autor: 'Clarice Lispector',
    editora: 'Rocco',
    image: 'https://m.media-amazon.com/images/I/810Vj9zyi-L._SL1500_.jpg',
  },
  {
    id: '11',
    name: 'Anna Kariênina',
    value: 17.98,
    autor: 'Liev Tolstoi',
    editora: 'Cia das Letras',
    image: 'https://m.media-amazon.com/images/I/61pTISHTptL._SL1457_.jpg',
  },
  {
    id: '12',
    name: 'A Metade Perdida',
    value: 14.80,
    autor: 'Brit Bennett',
    editora: 'Intrínseca',
    image: 'https://m.media-amazon.com/images/I/71Lb44nVKUL._SL1500_.jpg',
  },
  {
    id: '13',
    name: 'Tudo é rio',
    value: 12.92,
    autor: 'Carla Madeira',
    editora: 'Record',
    image: 'https://m.media-amazon.com/images/I/816Udvs9O7L._SL1500_.jpg',
  },
  {
    id: '14',
    name: 'Torto Arado',
    value: 16.82,
    autor: 'Itamar Vieira Junior',
    editora: 'Todavia',
    image: 'https://m.media-amazon.com/images/I/61Sor5r12SL._SL1230_.jpg',
  },
  {
    id: '15',
    name: 'Hibisco Roxo',
    value: 39.97,
    autor: 'Chimamanda Ngozi Adichie',
    editora: 'Cia das Letras',
    image: 'https://m.media-amazon.com/images/I/81hobIPsJAL._SL1500_.jpg',
  },
  {
    id: '16',
    name: 'Em Busca de Mim',
    value: 26.67,
    autor: 'Viola Davis',
    editora: 'BestSeller',
    image: 'https://m.media-amazon.com/images/I/91J7EVQy1jL._SL1500_.jpg',
  },
  {
    id: '17',
    name: 'Pequeno Manual Antirracista',
    value: 33.92,
    autor: 'Djamila Ribeiro',
    editora: 'Cia das Letras',
    image: 'https://m.media-amazon.com/images/I/71D3cAdm0GL._SL1500_.jpg',
  },
  {
    id: '18',
    name: 'Mulherzinhas',
    value: 11.68,
    autor: 'Louisa May Alcott',
    editora: 'Via Leitura',
    image: 'https://m.media-amazon.com/images/I/81oK5no3iLL._SL1500_.jpg',
  },
  {
    id: '19',
    name: 'Emma',
    value: 10.36,
    autor: 'Jane Austen',
    editora: 'Tricaju',
    image: 'https://m.media-amazon.com/images/I/71COwZu-WbL._SL1300_.jpg',
  },
  {
    id: '20',
    name: 'O Alienista',
    value: 26.19,
    autor: 'Machado de Assis',
    editora: 'Nova Fronteira',
    image: 'https://m.media-amazon.com/images/I/71ePCUicIdL._SL1360_.jpg',
  },
  {
    id: '21',
    name: 'Frankenstein',
    value: 13.99,
    autor: 'Mary Shelley',
    editora: 'ASA',
    image: 'https://m.media-amazon.com/images/I/51nLfJecMlL.jpg',
  },
];
 