//Aqui temos os livros sendo "cadastrados" na lista books. O id é o que torna cada um exlusivo

export const books = [
    {
      id: '1',
      name: 'O mundo de Sofia',
      value: 20.0,
      editora: 'Cia das Letras',
      image: 'https://m.media-amazon.com/images/I/81KfUf8JkcL._SY425_.jpg',
    },
    {
      id: '2',
      name: 'O mundo de Sofia',
      value: 20.0,
      editora: 'Cia das Letras',
      image: 'https://m.media-amazon.com/images/I/81KfUf8JkcL._SY425_.jpg',
    },
    {
      id: '3',
      name: 'O mundo de Sofia',
      value: 20.0,
      editora: 'Cia das Letras',
      image: 'https://m.media-amazon.com/images/I/81KfUf8JkcL._SY425_.jpg',
    },
    {
      id: '4',
      name: 'O mundo de Sofia',
      value: 20.0,
      editora: 'Cia das Letras',
      image: 'https://m.media-amazon.com/images/I/81KfUf8JkcL._SY425_.jpg',
    },
    {
      id: '5',
      name: 'O mundo de Sofia',
      value: 20.0,
      editora: 'Cia das Letras',
      image: 'https://m.media-amazon.com/images/I/81KfUf8JkcL._SY425_.jpg',
    },
    {
      id: '6',
      name: 'O mundo de Sofia',
      value: 20.0,
      editora: 'Cia das Letras',
      image: 'https://m.media-amazon.com/images/I/81KfUf8JkcL._SY425_.jpg',
    },
    {
      id: '7',
      name: 'O mundo de Sofia',
      value: 20.0,
      editora: 'Cia das Letras',
      image: 'https://m.media-amazon.com/images/I/81KfUf8JkcL._SY425_.jpg',
    },
    {
      id: '8',
      name: 'O mundo de Sofia',
      value: 20.0,
      editora: 'Cia das Letras',
      image: 'https://m.media-amazon.com/images/I/81KfUf8JkcL._SY425_.jpg',
    },
    {
      id: '9',
      name: 'O mundo de Sofia',
      value: 20.0,
      editora: 'Cia das Letras',
      image: 'https://m.media-amazon.com/images/I/81KfUf8JkcL._SY425_.jpg',
    },
    {
      id: '10',
      name: 'O mundo de Sofia',
      value: 20.0,
      editora: 'Cia das Letras',
      image: 'https://m.media-amazon.com/images/I/81KfUf8JkcL._SY425_.jpg',
    },
    {
      id: '11',
      name: 'O mundo de Sofia',
      value: 20.0,
      editora: 'Cia das Letras',
      image: 'https://m.media-amazon.com/images/I/81KfUf8JkcL._SY425_.jpg',
    },
    {
      id: '12',
      name: 'O mundo de Sofia',
      value: 20.0,
      editora: 'Cia das Letras',
      image: 'https://m.media-amazon.com/images/I/81KfUf8JkcL._SY425_.jpg',
    },
    {
      id: '13',
      name: 'O mundo de Sofia',
      value: 20.0,
      editora: 'Cia das Letras',
      image: 'https://m.media-amazon.com/images/I/81KfUf8JkcL._SY425_.jpg',
    },
    {
      id: '14',
      name: 'O mundo de Sofia',
      value: 20.0,
      editora: 'Cia das Letras',
      image: 'https://m.media-amazon.com/images/I/81KfUf8JkcL._SY425_.jpg',
    },
    {
      id: '15',
      name: 'O mundo de Sofia',
      value: 20.0,
      editora: 'Cia das Letras',
      image: 'https://m.media-amazon.com/images/I/81KfUf8JkcL._SY425_.jpg',
    },
    {
      id: '16',
      name: 'O mundo de Sofia',
      value: 20.0,
      editora: 'Cia das Letras',
      image: 'https://m.media-amazon.com/images/I/81KfUf8JkcL._SY425_.jpg',
    },
    {
      id: '17',
      name: 'O mundo de Sofia',
      value: 20.0,
      editora: 'Cia das Letras',
      image: 'https://m.media-amazon.com/images/I/81KfUf8JkcL._SY425_.jpg',
    },
    {
      id: '18',
      name: 'O mundo de Sofia',
      value: 20.0,
      editora: 'Cia das Letras',
      image: 'https://m.media-amazon.com/images/I/81KfUf8JkcL._SY425_.jpg',
    },
    {
      id: '19',
      name: 'O mundo de Sofia',
      value: 20.0,
      editora: 'Cia das Letras',
      image: 'https://m.media-amazon.com/images/I/81KfUf8JkcL._SY425_.jpg',
    },
    {
      id: '20',
      name: 'O mundo de Sofia',
      value: 20.0,
      editora: 'Cia das Letras',
      image: 'https://m.media-amazon.com/images/I/81KfUf8JkcL._SY425_.jpg',
    },
    
  ];
   